version: 2
jobs:
  unit-tests:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install astropy codecov 'coverage<5' pytest pytest-astropy scipy "setuptools>=30.3"
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python setup.py test --coverage
      - run:
          name: Run codecov
          command: |
            . venv/bin/activate
            codecov
  code-style:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 "setuptools>=30.3"
      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            python setup.py flake8
  build-docs:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt update
            sudo apt install -y graphviz
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install scipy astropy sphinx-astropy "setuptools>=30.3"
      - run:
          name: Build Docs
          command: |
            . venv/bin/activate
            python setup.py build_docs
      - run:
          name: Prepare Upload
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ]; then
              # remove all docs if not a PR
              rm -r docs/_build/html
            else
              # remove extra files if a PR
              rm -r docs/_build/html/_sources
              rm -r docs/_build/html/_modules
              rm -r docs/_build/html/.doctrees
            fi
      - store_artifacts:
          path: docs/_build/html
          destination: html
workflows:
  version: 2
  run_all_checks:
    jobs:
      - unit-tests
      - code-style
      - build-docs
notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
