name: Pull Request
on: [pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astropy pytest pytest-astropy scipy "setuptools>=30.3"
    - name: Add pytest Matcher
      run: |
        echo ::add-matcher::.github/problem_matchers/pytest.json
    - name: Run Tests
      run: |
        python setup.py test
  flake8:
    name: Code Issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 "setuptools>=30.3"
    - name: Add flake8 Matcher
      run: |
        echo ::add-matcher::.github/problem_matchers/flake8.json
    - name: Run flake8
      run: |
        python setup.py flake8
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scipy matplotlib astropy "sphinx==2.*" sphinx-astropy "setuptools>=30.3"
    - name: Add sphinx Matcher
      run: |
        echo ::add-matcher::.github/problem_matchers/sphinx.json
    - name: Build Docs
      run: |
        python setup.py build_docs
    - name: Clean Docs
      run: |
        rm -r docs/_build/html/{_sources,_modules,.doctrees}
    - name: Upload Docs
      uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: docs/_build/html
